//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.5.15
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: tt_um_test_nand ()
//
module tt_um_test_nand // "tb.dut_inst"
(
    input logic [7:0] ui_in,
    output logic [7:0] uo_out,
    input logic [7:0] uio_in,
    output logic [7:0] uio_out,
    output logic [7:0] uio_oe,
    input logic ena,
    input logic clk,
    input logic rst_n
);

//------------------------------------------------------------------------------
// Method process: process (test_nand.cpp:19:3) 

always_comb 
begin : process     // test_nand.cpp:19:3
    uo_out = !(ui_in[0] && ui_in[1]);
    uio_out = 0;
    uio_oe = 0;
end

endmodule


